### ISSUE TITLE
Ruby2.4アップデート

### ISSUE THREAD

**Issue by shu0115** [shu0115/calem#29]
Ruby 2.4.1 + Rails 4.2.6だと↓下記エラー

```
bundle exec rails s
----------
=> Booting Puma
=> Rails 4.2.6 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Exiting
/Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5534 levels...
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/shun.matsumoto/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by shu0115** [comment]
- [Rails5アップデート · Issue #28 · shu0115/calem](https://github.com/shu0115/calem/issues/28)

DONE
